{
    "openapi": "3.0.0",
    "info": {
        "title": "Agenda aluno",
        "description": "Nossa aplicação se trata de uma agenda voltada para alunos, para que os estudantes possam se organizar melhor com relação aos trabalhos, provas e atividades.",
        "contact": {},
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http:localhost:8000/doc",
            "description": "Documentação"
        }
    ],
    "paths": {
        "/aluno": {
            "post": {
                "summary": "Cadastro de aluno",
                "description": "Essa rota é responsável por criar um novo aluno",
                "tags": ["Aluno"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schema/aluno"
                            },
                            "examples": {
                                "aluno": {
                                    "value": {
                                        "id":"1",
                                        "name": "Maria",
                                        "telefone": "9999-9999",
                                        "email": "maria@maria.com",
                                        "ususario": "Maria456",
                                        "senha": "Senha@maria123"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schema/aluno"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/aluno/{idAluno}":{
            "get":{
                "description":"Busca aluno pelo id",
                "summary":"Busca aluno pelo id",
                "tags": ["Aluno"],
                "parameters":[
                    {
                        "name":"id",
                        "in":"query",
                        "description":"Id para buscar o aluno",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items":{
                                      "$ref": "#/components/schema/aluno"  
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    } 
                }
            },
            "put":{
                "description":"Edita cadastro do aluno",
                "summary":"Edita cadastro do aluno",
                "tags": ["Aluno"],
                "parameters":[
                    {
                        "name":"id",
                        "in":"path",
                        "description":"Id para buscar o aluno",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schema/aluno"
                            },
                            "examples": {
                                "aluno": {
                                    "value": {
                                        "id":"1",
                                        "name": "Maria Silva",
                                        "telefone": "9999-9999",
                                        "email": "maria@maria.com",
                                        "ususario": "Maria456",
                                        "senha": "Senha@maria123"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items":{
                                      "$ref": "#/components/schema/aluno"  
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    } 
                }
            },
            "delete":{
                "description":"Deleta cadastro do aluno",
                "summary":"Deleta cadastro do aluno",
                "tags": ["Aluno"],
                "parameters":[
                    {
                        "name":"id",
                        "in":"query",
                        "description":"Delete aluno cadastrado",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    } 
                }
            }
        },
        "/aluno//alterarSenha/{id}":{
            "put":{
                "description":"Edita senha do aluno",
                "summary":"Edita senha do aluno",
                "tags": ["Aluno"],
                "parameters":[
                    {
                        "name":"usuario",
                        "in":"path",
                        "description":"Edita senha do aluno",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schema/senha"
                            },
                            "examples": {
                                "senha": {
                                    "value": {
                                        "ususario": "Maria456",
                                        "senha": "Senha@maria123"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "500": {
                        "description":"Internal server error"
                    },
                    "401": {
                        "description": "Unauthorized"
                    } 
                }
            }
        },
        "/login": {
            "post": {
                "summary": "Login de aluno",
                "description": "Essa rota é responsável por realizar o login do aluno",
                "tags": [
                    "Login"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schema/login"
                            },
                            "examples": {
                                "login": {
                                    "value": {
                                        "email": "maria@maria.com",
                                        "senha": "Senha@maria123"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schema/login"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/disciplina": {
            "post": {
                "summary": "Cria disciplina",
                "description": "Essa rota é responsável por criar disciplinas",
                "tags": [
                    "Disciplina"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schema/disciplina"
                            },
                            "examples": {
                                "disciplina": {
                                    "value": {
                                        "id":"1",
                                        "name": "Matematica",
                                        "abreviacao": "MAT",
                                        "docente": "Maria",
                                        "anotacao": "Prova sobre raiz quadrada"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schema/disciplina"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            },
            "get": {
                "summary": "Busca todas as disciplinas",
                "description": "Essa rota é responsável por buscar todas as disciplinas",
                "tags": [
                    "Disciplina"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schema/disciplina"
                            },
                            "examples": {
                                "disciplina": {
                                    "value": {
                                        "id":"1",
                                        "name": "Matematica",
                                        "abreviacao": "MAT",
                                        "docente": "Maria",
                                        "anotacao": "Prova sobre raiz quadrada"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schema/disciplina"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/disciplina/{id}":{
            "get":{
                "description":"Busca disciplina por id",
                "summary":"Busca disciplina por id",
                "tags": ["Disciplina"],
                "parameters":[
                    {
                        "name":"id",
                        "in":"query",
                        "description":"Id para buscar a disciplina",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items":{
                                      "$ref": "#/components/schema/aluno"  
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    } 
                }
            },
            "put":{
                "description":"Edita disciplina",
                "summary":"Edita disciplina",
                "tags": ["Disciplina"],
                "parameters":[
                    {
                        "name":"id",
                        "in":"path",
                        "description":"Id para buscar e editar disciplina",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schema/disciplina"
                            },
                            "examples": {
                                "disciplina": {
                                    "value": {
                                        "id":"1",
                                        "name": "Matematica",
                                        "abreviacao": "MAT",
                                        "docente": "Maria",
                                        "anotacao": "Comprar uma regua para realizar o trabalho"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items":{
                                      "$ref": "#/components/schema/disciplina"  
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    } 
                }
            },
            "delete":{
                "description":"Deleta disciplina",
                "summary":"Deleta disciplina",
                "tags": ["Disciplina"],
                "parameters":[
                    {
                        "name":"id",
                        "in":"query",
                        "description":"Id para deletar disciplina",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    } 
                }
            }
        },
        "/instituicao": {
            "post": {
                "summary": "Cria instituição",
                "description": "Essa rota é responsável por criar uma instituição",
                "tags": ["Instituicao"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schema/instituicao"
                            },
                            "examples": {
                                "instituicao": {
                                    "value": {
                                        "id":"1",
                                        "nome": "Proway",
                                        "sigla": "PrW",
                                        "cep": "89010-204",
                                        "rua": "R. 7 de Setembro",
                                        "cidade":"Blumenau",
                                        "estado":"Santa Catarina"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schema/instituicao"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            },
            "get": {
                "summary": "Busca todas as instituicoes",
                "description": "Essa rota é responsável por buscar todas as instituicoes",
                "tags": ["Instituicao"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schema/instituicao"
                            },
                            "examples": {
                                "instituicao": {
                                    "value": {
                                        "id":"1",
                                        "nome": "Proway",
                                        "sigla": "PrW",
                                        "cep": "89010-204",
                                        "rua": "R. 7 de Setembro",
                                        "cidade":"Blumenau",
                                        "estado":"Santa Catarina"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schema/instituicao"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/instituicao/{id}":{
            "get":{
                "description":"Busca instituicao por id",
                "summary":"Busca instituicao por id",
                "tags": ["Instituicao"],
                "parameters":[
                    {
                        "name":"id",
                        "in":"query",
                        "description":"Id para buscar a instituicao",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items":{
                                      "$ref": "#/components/schema/instituicao"  
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    } 
                }
            },
            "put":{
                "description":"Edita instituicao",
                "summary":"Edita instituicao",
                "tags": ["Instituicao"],
                "parameters":[
                    {
                        "name":"id",
                        "in":"path",
                        "description":"Id para buscar e editar instituicao",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schema/instituicao"
                            },
                            "examples": {
                                "instituicao": {
                                    "value": {
                                        "id":"1",
                                        "nome": "ProWay",
                                        "sigla": "PrW",
                                        "cep": "89010-204",
                                        "rua": "R. 7 de Setembro",
                                        "cidade":"Blumenau",
                                        "estado":"Santa Catarina"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items":{
                                      "$ref": "#/components/schema/instituicao"  
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    } 
                }
            },
            "delete":{
                "description":"Deleta instituicao",
                "summary":"Deleta instituicao",
                "tags": ["Instituicao"],
                "parameters":[
                    {
                        "name":"id",
                        "in":"query",
                        "description":"Id para deletar instituicao",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    } 
                }
            }
        },
        "/nota": {
            "post": {
                "summary": "Cria nota",
                "description": "Essa rota é responsável por criar uma nota",
                "tags": ["Nota"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schema/nota"
                            },
                            "examples": {
                                "nota": {
                                    "value": {
                                        "id":"1",
                                        "descricao": "Prova II",
                                        "nota": "9"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schema/nota"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            },
            "delete":{
                "description":"Deleta nota",
                "summary":"Deleta nota",
                "tags": ["Nota"],
                "parameters":[
                    {
                        "name":"id",
                        "in":"query",
                        "description":"Id para deletar nota",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    } 
                }
            }
        },
        "/nota/{iddisc}":{
            "get":{
                "description":"Busca nota por id da disciplina",
                "summary":"Busca as notas que estão relacionadas a uma disciplina",
                "tags": ["Nota"],
                "parameters":[
                    {
                        "name":"id",
                        "in":"query",
                        "description":"Id para buscar a nota por disciplina",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items":{
                                      "$ref": "#/components/schema/nota"  
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    } 
                }
            }
        }
    },
    "components": {
        "schema": {
            "aluno": {
                "type": "object",
                "properties": {
                    "id":{
                        "id":"1"
                    },
                    "nome": {
                        "type": "string"
                    },
                    "telefone": {
                        "type": "number"
                    },
                    "email": {
                        "type": "string"
                    },
                    "usuario": {
                        "type": "string"
                    },
                    "senha": {
                        "type": "string"
                    }
                }
            },
            "login":{
                "type":"object",
                "properties":{
                    "email":{
                        "type":"string"
                    },
                    "senha":{
                        "type":"string"
                    }
                }
            },
            "disciplina":{
                "type":"object",
                "properties":{
                    "nome":{
                        "type":"string"
                    },
                    "abreviacao":{
                        "type":"string"
                    },
                    "docente":{
                        "type":"string"
                    },
                    "anotacao":{
                        "type":"string"
                    }
                }
            },
            "instituicao":{
                "type":"object",
                "properties":{
                    "nome":{
                        "type":"string"
                    },
                    "sigla":{
                        "type":"string"
                    },
                    "cep":{
                        "type":"string"
                    },
                    "rua":{
                        "type":"string"
                    },
                    "cidade":{
                        "type":"string"
                    },
                    "estado":{
                        "type":"string"
                    }
                }
            },
            "nota":{
                "type":"object",
                "properties":{
                    "descricao":{
                        "type":"string"
                    },
                    "nota":{
                        "type":"number"
                    }
                }
            },
            "senha":{
                "type":"object",
                "properties":{
                    "usuario":{
                        "type":"string"
                    },
                    "senha":{
                        "type":"string"
                    }
                }
            }
        }
    }
}